
arj e d:\karat\optonov\dbf\bax508.arj  baxta0.5 -Jk -r 
arj e d:\karat\optonov\dbf\bax508.arj  baxta1.5 -Jk -r 
arj e d:\karat\optonov\dbf\bax508.arj  baxta2.5 -Jk -r 
arj e d:\karat\optonov\dbf\bax508.arj  baxta3.5 -Jk -r 
arj e d:\karat\optonov\dbf\bax508.arj  baxta4.5 -Jk -r 
rename baxta0.5 baxta0.dbf
rename baxta1.5 baxta1.dbf
rename baxta2.5 baxta2.dbf
rename baxta3.5 baxta3.dbf
rename baxta4.5 baxta4.dbf
pause